services:
  - type: web
    name: two-js-beverage
    env: static
    staticPublishPath: .
    buildCommand: echo "static"
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
